# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialMedia' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  
  pod 'LinkedinSwift', '>= 1.6.2'
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'InstagramKit', '~> 3.0'

end
